name: CI
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo pip3 install cmake
        sudo apt-get update
        sudo apt-get install -y qt5-default


  build_emulator:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: cd build && cmake .. && make -j4
  
  build_zybo:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: cd build && cmake .. -DBOARD=1 && make -j4
  

  check_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check C/C++ formatting
      run: ./format.py --check --all

  check_and_zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run check_and_zip.py
      run: ./check_and_zip.py --no_run lab1